worker_processes auto;

events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=10s;
    client_max_body_size 100M;

    server {
        listen 80 default_server;
        server_name _;
        return 404;
    }

    include /etc/nginx/instances/*.conf;
}
